firstJoin_message: '&a<player> &7has joined the server for the first time!;&a<player> &7is a &cFirst Timer&7! Welcome!;A new player has joined: &a<player>'

join_message: '&e<player> &7just hopped into the server!;&e<player> &7just popped into existence!;&e<player> &7finally landed on the server!'
